#!/bin/bash


## Load the required modules
#module load mpt
#module load intel-compilers-19

## compile


## compile with MPI:
mpicxx 2DWaveX.cpp -o 2DWaveX

## remove object files if there is any!:
# rm *.mod
# rm *.o

